/**
 * Knihovna cviků pro seed.
 *
 * Pokrývá běžný rozsah posilovny: velká činka, jednoručky, kladky, stroje,
 * vlastní váha, kettlebell, gumy a kardio. Názvy jsou české, jak je používají
 * trenéři v ČR; u zavedených anglických pojmů (bench press, hip thrust)
 * zůstává vžitý název, protože klienti jiný neznají.
 *
 * Kategorie musí odpovídat EXERCISE_CATEGORIES v src/lib/enums.ts.
 */

export type ExerciseSeed = {
  name: string;
  category: string;
  muscleGroup: string;
  equipment: string;
  instructions: string;
};

export const EXERCISES: ExerciseSeed[] = [
  // ------------------------------------------------------------------ PRSA
  { name: "Bench press", category: "Prsa", muscleGroup: "Velký prsní sval", equipment: "Velká činka", instructions: "Lehněte si na lavici, chodidla pevně na zemi. Činku spouštějte pomalu ke středu hrudníku, lokty svírají s tělem zhruba 45°. Vytlačte nahoru bez záklonu v zádech." },
  { name: "Bench press na šikmé lavici", category: "Prsa", muscleGroup: "Horní část prsou", equipment: "Velká činka", instructions: "Lavice nastavená na 30°. Činku spouštějte k horní části hrudníku, lopatky stažené k sobě." },
  { name: "Bench press hlavou dolů", category: "Prsa", muscleGroup: "Dolní část prsou", equipment: "Velká činka", instructions: "Lavice v mírném záporném sklonu. Činku spouštějte k dolní části hrudníku." },
  { name: "Bench press úzkým úchopem", category: "Prsa", muscleGroup: "Prsa a triceps", equipment: "Velká činka", instructions: "Ruce na šíři ramen. Lokty veďte podél těla, ne do stran." },
  { name: "Tlaky s jednoručkami na rovné lavici", category: "Prsa", muscleGroup: "Velký prsní sval", equipment: "Jednoručky", instructions: "Jednoručky tlačte nahoru a mírně k sobě, dolů spouštějte do protažení hrudníku." },
  { name: "Tlaky s jednoručkami na šikmé lavici", category: "Prsa", muscleGroup: "Horní část prsou", equipment: "Jednoručky", instructions: "Lavici nastavte na 30°. Jednoručky tlačte nahoru a mírně k sobě, dolů spouštějte kontrolovaně do protažení." },
  { name: "Rozpažování s jednoručkami", category: "Prsa", muscleGroup: "Velký prsní sval", equipment: "Jednoručky", instructions: "Lokty jemně pokrčené po celou dobu. Rozpažujte do protažení, pak sveďte nad hrudník." },
  { name: "Rozpažování na šikmé lavici", category: "Prsa", muscleGroup: "Horní část prsou", equipment: "Jednoručky", instructions: "Lavice na 30°. Pohyb veďte obloukem, lokty zůstávají jemně pokrčené." },
  { name: "Rozpažování na kladce", category: "Prsa", muscleGroup: "Velký prsní sval", equipment: "Kladka", instructions: "Mírný předklon, lokty jemně pokrčené. Ruce svádějte před tělem a na vteřinu zastavte." },
  { name: "Peck deck", category: "Prsa", muscleGroup: "Velký prsní sval", equipment: "Stroj", instructions: "Záda opřená, lokty ve výši ramen. Svádějte opěrky před tělem a zadržte." },
  { name: "Tlaky na prsa na stroji", category: "Prsa", muscleGroup: "Velký prsní sval", equipment: "Stroj", instructions: "Sedněte tak, aby madla byla ve výši středu hrudníku. Tlačte vpřed bez zamykání loktů." },
  { name: "Kliky", category: "Prsa", muscleGroup: "Prsa a triceps", equipment: "Vlastní váha", instructions: "Tělo drží přímku od hlavy k patám. Spouštějte se, dokud hrudník není kousek nad zemí." },
  { name: "Kliky s nohama na lavici", category: "Prsa", muscleGroup: "Horní část prsou", equipment: "Vlastní váha", instructions: "Nohy na lavici, tělo v přímce. Náročnější varianta běžných kliků." },
  { name: "Kliky úzkým úchopem", category: "Prsa", muscleGroup: "Prsa a triceps", equipment: "Vlastní váha", instructions: "Ruce blízko sebe pod hrudníkem, lokty podél těla." },
  { name: "Kliky na bradlech pro prsa", category: "Prsa", muscleGroup: "Dolní část prsou", equipment: "Bradla", instructions: "Trup nakloňte vpřed a lokty rozevřete mírně do stran — zapojí se víc prsa než triceps." },
  { name: "Přetahy s jednoručkou přes lavici", category: "Prsa", muscleGroup: "Prsa a široký sval zádový", equipment: "Jednoručky", instructions: "Leh napříč lavicí. Jednoručku veďte obloukem za hlavu do protažení a zpět nad hrudník." },

  // ------------------------------------------------------------------ ZÁDA
  { name: "Mrtvý tah", category: "Záda", muscleGroup: "Vzpřimovače a hýždě", equipment: "Velká činka", instructions: "Činka nad středem chodidla, záda rovná. Vedení tahu přes paty, boky a ramena stoupají současně." },
  { name: "Mrtvý tah sumo", category: "Záda", muscleGroup: "Vzpřimovače, hýždě a stehna", equipment: "Velká činka", instructions: "Široký postoj, ruce uvnitř kolen. Trup zůstává vzpřímenější než u klasického mrtvého tahu." },
  { name: "Přítahy velké činky v předklonu", category: "Záda", muscleGroup: "Široký sval zádový", equipment: "Velká činka", instructions: "Předklon zhruba 45°, záda rovná. Činku táhněte k pupku, lopatky stahujte k sobě." },
  { name: "Přítahy velké činky podhmatem", category: "Záda", muscleGroup: "Široký sval zádový a biceps", equipment: "Velká činka", instructions: "Podhmat na šíři ramen. Táhněte k dolní části břicha, lokty veďte podél těla." },
  { name: "Přítahy jednoručky v podporu", category: "Záda", muscleGroup: "Široký sval zádový", equipment: "Jednoručky", instructions: "Koleno a ruka opřené o lavici. Jednoručku táhněte k boku, ne k rameni." },
  { name: "Přítahy v T-baru", category: "Záda", muscleGroup: "Střední část zad", equipment: "T-bar", instructions: "Předklon s rovnými zády, madlo táhněte k hrudníku a lopatky stahujte." },
  { name: "Shyby", category: "Záda", muscleGroup: "Široký sval zádový", equipment: "Hrazda", instructions: "Nadhmatem na šíři ramen. Táhněte se, dokud brada nepřejde hrazdu, dolů kontrolovaně do napnutých paží." },
  { name: "Shyby podhmatem", category: "Záda", muscleGroup: "Široký sval zádový a biceps", equipment: "Hrazda", instructions: "Podhmat na šíři ramen. Zapojí se víc biceps než u nadhmatu." },
  { name: "Shyby s dopomocí gumy", category: "Záda", muscleGroup: "Široký sval zádový", equipment: "Hrazda a guma", instructions: "Gumu zavěste na hrazdu a opřete o ni koleno. Vhodné, dokud shyb nezvládnete sami." },
  { name: "Stahování horní kladky", category: "Záda", muscleGroup: "Široký sval zádový", equipment: "Kladka", instructions: "Hrudník vzhůru, tyč táhněte k horní části hrudníku. Netahejte za hlavu." },
  { name: "Stahování horní kladky úzkým úchopem", category: "Záda", muscleGroup: "Široký sval zádový", equipment: "Kladka", instructions: "Paralelní madlo, lokty veďte podél těla k bokům." },
  { name: "Veslování na spodní kladce", category: "Záda", muscleGroup: "Střední část zad", equipment: "Kladka", instructions: "Sed vzpřímeně, rukojeť táhněte k břichu, lopatky k sobě." },
  { name: "Veslování na stroji", category: "Záda", muscleGroup: "Střední část zad", equipment: "Stroj", instructions: "Hrudník opřený o opěrku, táhněte lokty vzad a lopatky stahujte." },
  { name: "Přítahy horní kladky ve stoji", category: "Záda", muscleGroup: "Široký sval zádový", equipment: "Kladka", instructions: "Paže napnuté, tlačte tyč obloukem dolů k stehnům. Pohyb jde jen z ramenního kloubu." },
  { name: "Hyperextenze", category: "Záda", muscleGroup: "Vzpřimovače páteře", equipment: "Římská lavice", instructions: "Trup spouštějte do předklonu a zvedejte do roviny s nohama. Neprohýbejte se přes rovinu." },
  { name: "Good morning", category: "Záda", muscleGroup: "Vzpřimovače a hamstringy", equipment: "Velká činka", instructions: "Činka na zádech, kolena jemně pokrčená. Boky posouvejte vzad, záda držte rovná." },
  { name: "Rack pull", category: "Záda", muscleGroup: "Horní část zad a vzpřimovače", equipment: "Velká činka", instructions: "Činka na stojanech pod koleny. Zkrácený mrtvý tah, umožní vyšší váhu." },
  { name: "Šrugy s velkou činkou", category: "Záda", muscleGroup: "Trapézový sval", equipment: "Velká činka", instructions: "Ramena zvedejte přímo vzhůru, nahoře na vteřinu zadržte. Nekružte rameny." },
  { name: "Šrugy s jednoručkami", category: "Záda", muscleGroup: "Trapézový sval", equipment: "Jednoručky", instructions: "Jednoručky podél těla, ramena zvedejte kolmo vzhůru." },
  { name: "Přítahy k bradě", category: "Záda", muscleGroup: "Trapéz a ramena", equipment: "Velká činka", instructions: "Táhněte činku podél těla k hrudní kosti, lokty vedou pohyb. Netahejte výš než k bradě." },
  { name: "Face pull", category: "Záda", muscleGroup: "Zadní delty a trapéz", equipment: "Kladka", instructions: "Lano ve výši obličeje, táhněte k čelu a lokty rozevírejte do stran." },

  // ---------------------------------------------------------------- RAMENA
  { name: "Tlaky na ramena s velkou činkou", category: "Ramena", muscleGroup: "Deltový sval", equipment: "Velká činka", instructions: "Ve stoji nebo v sedu. Činku tlačte nad hlavu, hlavu při průchodu mírně zakloňte." },
  { name: "Tlaky na ramena s jednoručkami", category: "Ramena", muscleGroup: "Deltový sval", equipment: "Jednoručky", instructions: "Sed s opřenými zády. Jednoručky tlačte nad hlavu, dolů spouštějte do úrovně uší." },
  { name: "Arnoldovy tlaky", category: "Ramena", muscleGroup: "Přední a střední hlava deltu", equipment: "Jednoručky", instructions: "Začněte dlaněmi k sobě před obličejem, při tlaku nahoru rotujte předloktí." },
  { name: "Tlaky na ramena na stroji", category: "Ramena", muscleGroup: "Deltový sval", equipment: "Stroj", instructions: "Záda opřená, madla ve výši ramen. Tlačte nahoru bez zamykání loktů." },
  { name: "Upažování", category: "Ramena", muscleGroup: "Střední hlava deltu", equipment: "Jednoručky", instructions: "Lokty jemně pokrčené, upažujte do výše ramen. Netrhejte tělem." },
  { name: "Upažování na kladce", category: "Ramena", muscleGroup: "Střední hlava deltu", equipment: "Kladka", instructions: "Kladka u země, upažujte jednoruč do výše ramene. Odpor je stejný po celé dráze." },
  { name: "Upažování na stroji", category: "Ramena", muscleGroup: "Střední hlava deltu", equipment: "Stroj", instructions: "Předloktí opřená o opěrky, rozevírejte do stran do výše ramen." },
  { name: "Předpažování", category: "Ramena", muscleGroup: "Přední hlava deltu", equipment: "Jednoručky", instructions: "Střídavě předpažujte do výše ramen, tělo zůstává v klidu." },
  { name: "Předpažování s kotoučem", category: "Ramena", muscleGroup: "Přední hlava deltu", equipment: "Kotouč", instructions: "Kotouč držte po stranách, zvedejte před tělo do výše očí." },
  { name: "Rozpažování v předklonu", category: "Ramena", muscleGroup: "Zadní hlava deltu", equipment: "Jednoručky", instructions: "Předklon, záda rovná. Rozpažujte do stran, lopatky stahujte." },
  { name: "Rozpažování na stroji", category: "Ramena", muscleGroup: "Zadní hlava deltu", equipment: "Stroj", instructions: "Hrudník opřený, rozevírejte paže vzad do roviny ramen." },
  { name: "Rozpažování na kladkách", category: "Ramena", muscleGroup: "Zadní hlava deltu", equipment: "Kladka", instructions: "Kladky křížem ve výši ramen, rozevírejte paže do stran a vzad." },
  { name: "Tlaky nad hlavu s kettlebellem", category: "Ramena", muscleGroup: "Deltový sval", equipment: "Kettlebell", instructions: "Kettlebell v zákluzu na předloktí. Tlačte nad hlavu, střed těla zpevněný." },
  { name: "Landmine press", category: "Ramena", muscleGroup: "Přední hlava deltu", equipment: "Landmine", instructions: "Konec osy v rohu, tlačte šikmo vzhůru před tělem. Šetrné k ramennímu kloubu." },

  // ---------------------------------------------------------------- BICEPS
  { name: "Bicepsový zdvih s velkou činkou", category: "Biceps", muscleGroup: "Dvojhlavý sval pažní", equipment: "Velká činka", instructions: "Lokty u těla, činku zvedejte bez houpání trupem." },
  { name: "Bicepsový zdvih s EZ osou", category: "Biceps", muscleGroup: "Dvojhlavý sval pažní", equipment: "EZ osa", instructions: "Lomená osa šetří zápěstí. Lokty zůstávají u těla." },
  { name: "Bicepsový zdvih s jednoručkami", category: "Biceps", muscleGroup: "Dvojhlavý sval pažní", equipment: "Jednoručky", instructions: "Střídavě nebo současně. V horní poloze dlaně mírně rotujte ven." },
  { name: "Kladivové zdvihy", category: "Biceps", muscleGroup: "Biceps a předloktí", equipment: "Jednoručky", instructions: "Dlaně proti sobě po celou dobu pohybu. Lokty zůstávají u těla." },
  { name: "Bicepsový zdvih na kazatelně", category: "Biceps", muscleGroup: "Dvojhlavý sval pažní", equipment: "EZ osa", instructions: "Paže opřené o podložku. Dolů spouštějte pomalu do téměř napnutých loktů." },
  { name: "Bicepsový zdvih na kladce", category: "Biceps", muscleGroup: "Dvojhlavý sval pažní", equipment: "Kladka", instructions: "Kladka u země. Odpor drží napětí i v dolní poloze." },
  { name: "Koncentrovaný zdvih", category: "Biceps", muscleGroup: "Dvojhlavý sval pažní", equipment: "Jednoručky", instructions: "V sedu opřete loket o vnitřní stranu stehna a zvedejte jednoruč." },
  { name: "Zdvih v předklonu na šikmé lavici", category: "Biceps", muscleGroup: "Dlouhá hlava bicepsu", equipment: "Jednoručky", instructions: "Leh na šikmé lavici, paže volně visí. Zvedejte bez pohybu ramen." },
  { name: "Bicepsový zdvih se zvratem", category: "Biceps", muscleGroup: "Předloktí a biceps", equipment: "EZ osa", instructions: "Nadhmat. Zapojí se hlavně horní část předloktí." },
  { name: "Bicepsový zdvih s gumou", category: "Biceps", muscleGroup: "Dvojhlavý sval pažní", equipment: "Guma", instructions: "Gumu přišlápněte, zvedejte s lokty u těla. Odpor roste směrem nahoru." },

  // --------------------------------------------------------------- TRICEPS
  { name: "Tricepsové stahování kladky", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "Kladka", instructions: "Lokty přitisknuté k tělu, pohyb vychází jen z předloktí." },
  { name: "Tricepsové stahování s lanem", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "Kladka", instructions: "Dole lano rozevřete do stran a na vteřinu zadržte." },
  { name: "Francouzský tlak", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "EZ osa", instructions: "Vleže spouštějte osu k čelu, lokty směřují vzhůru a nerozjíždějí se." },
  { name: "Francouzský tlak s jednoručkou nad hlavou", category: "Triceps", muscleGroup: "Dlouhá hlava tricepsu", equipment: "Jednoručky", instructions: "Jednoručku držte obouruč nad hlavou, spouštějte za hlavu s lokty u sebe." },
  { name: "Tricepsové kliky na bradlech", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "Bradla", instructions: "Trup mírně vpřed. Spouštějte se do 90° v lokti a vytlačte zpět." },
  { name: "Tricepsové kliky mezi lavicemi", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "Lavice", instructions: "Ruce za tělem na lavici, nohy natažené. Spouštějte boky dolů a vytlačte." },
  { name: "Kickback", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "Jednoručky", instructions: "V předklonu propínejte paži vzad, rameno zůstává v klidu." },
  { name: "Tlaky úzkým úchopem na stroji", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "Stroj", instructions: "Madla blízko sebe, lokty veďte podél těla." },
  { name: "Tricepsové stahování jednoruč", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "Kladka", instructions: "Podhmat jednou rukou. Umožní soustředit se na slabší paži." },
  { name: "Diamantové kliky", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "Vlastní váha", instructions: "Palce a ukazováky tvoří trojúhelník pod hrudníkem. Lokty podél těla." },

  // ------------------------------------------------------------------ NOHY
  { name: "Dřep s velkou činkou", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Velká činka", instructions: "Činka na horní části zad, chodidla na šíři ramen. Klesejte do podřepu se zády v přirozeném prohnutí, kolena sledují špičky." },
  { name: "Přední dřep", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Velká činka", instructions: "Činka na přední straně ramen, lokty vysoko. Trup zůstává vzpřímenější než u zadního dřepu." },
  { name: "Dřep s kettlebellem", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Kettlebell", instructions: "Kettlebell držte u hrudníku. Vhodné pro nácvik správné hloubky dřepu." },
  { name: "Dřep v Smithově stroji", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Smith stroj", instructions: "Chodidla mírně před tělem. Vedená dráha usnadní udržení techniky." },
  { name: "Hack dřep", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Stroj", instructions: "Záda opřená o opěrku, chodidla na šíři ramen. Klesejte do 90° v koleni." },
  { name: "Leg press", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Stroj", instructions: "Chodidla na šíři ramen. Spouštějte kontrolovaně, kolena nezamykejte v horní pozici." },
  { name: "Leg press jednonož", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Stroj", instructions: "Jedna noha uprostřed plošiny. Odhalí rozdíl mezi stranami." },
  { name: "Výpady s jednoručkami", category: "Nohy", muscleGroup: "Stehna a hýždě", equipment: "Jednoručky", instructions: "Krok vpřed, zadní koleno klesá k zemi. Trup zůstává vzpřímený." },
  { name: "Výpady vzad", category: "Nohy", muscleGroup: "Stehna a hýždě", equipment: "Jednoručky", instructions: "Krok vzad místo vpřed — šetrnější ke kolenům." },
  { name: "Chodící výpady", category: "Nohy", muscleGroup: "Stehna a hýždě", equipment: "Jednoručky", instructions: "Postupujte vpřed střídavými výpady po celé délce prostoru." },
  { name: "Bulharský dřep", category: "Nohy", muscleGroup: "Stehna a hýždě", equipment: "Jednoručky", instructions: "Zadní noha opřená o lavici. Váha spočívá na přední noze." },
  { name: "Výstupy na bednu", category: "Nohy", muscleGroup: "Stehna a hýždě", equipment: "Bedna", instructions: "Vystupte celou plochou chodidla, dolů kontrolovaně. Netlačte se zadní nohou." },
  { name: "Předkopávání na stroji", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Stroj", instructions: "Nahoře na vteřinu zastavte a stehno napněte." },
  { name: "Zakopávání na stroji", category: "Nohy", muscleGroup: "Hamstringy", equipment: "Stroj", instructions: "Pohyb veďte pomalu, boky zůstávají na podložce." },
  { name: "Zakopávání v sedu", category: "Nohy", muscleGroup: "Hamstringy", equipment: "Stroj", instructions: "Sed s opřenými zády, patami táhněte pod sebe." },
  { name: "Nordic curl", category: "Nohy", muscleGroup: "Hamstringy", equipment: "Vlastní váha", instructions: "Kotníky zafixované, tělo spouštějte vpřed jen silou zadních stehen." },
  { name: "Výpony ve stoji", category: "Nohy", muscleGroup: "Lýtka", equipment: "Stroj", instructions: "Paty spouštějte hluboko pod úroveň schůdku, nahoře zadržte." },
  { name: "Výpony v sedu", category: "Nohy", muscleGroup: "Šikmý sval lýtkový", equipment: "Stroj", instructions: "Kolena pokrčená v 90°. Zaměřuje hlouběji uložený lýtkový sval." },
  { name: "Výpony s velkou činkou", category: "Nohy", muscleGroup: "Lýtka", equipment: "Velká činka", instructions: "Činka na zádech, špičky na schůdku. Pohyb veďte pomalu." },
  { name: "Sissy dřep", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Vlastní váha", instructions: "Kolena posouvejte vpřed a zaklánějte se. Náročné na kolena — jen po zvládnutí techniky." },
  { name: "Goblet dřep", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Jednoručky", instructions: "Jednoručku držte svisle u hrudníku, klesejte mezi kolena." },
  { name: "Abdukce na stroji", category: "Nohy", muscleGroup: "Odtahovače stehna", equipment: "Stroj", instructions: "Kolena roztlačujte od sebe proti odporu, nahoře zadržte." },
  { name: "Addukce na stroji", category: "Nohy", muscleGroup: "Přitahovače stehna", equipment: "Stroj", instructions: "Kolena svádějte k sobě proti odporu, pohyb veďte pomalu." },

  // ----------------------------------------------------------------- HÝŽDĚ
  { name: "Hip thrust", category: "Hýždě", muscleGroup: "Velký sval hýžďový", equipment: "Velká činka", instructions: "Lopatky opřené o lavici. Boky zvedejte do roviny s trupem a nahoře hýždě sevřete." },
  { name: "Hip thrust jednonož", category: "Hýždě", muscleGroup: "Velký sval hýžďový", equipment: "Vlastní váha", instructions: "Jedna noha ve vzduchu. Boky držte v rovině, nenaklánějte je." },
  { name: "Glute bridge", category: "Hýždě", muscleGroup: "Velký sval hýžďový", equipment: "Vlastní váha", instructions: "Leh na zemi, boky zvedejte vzhůru a nahoře hýždě sevřete." },
  { name: "Rumunský mrtvý tah", category: "Hýždě", muscleGroup: "Hýždě a hamstringy", equipment: "Velká činka", instructions: "Nohy téměř napnuté, boky posouvejte vzad. Cítíte tah v zadní straně stehen." },
  { name: "Rumunský mrtvý tah s jednoručkami", category: "Hýždě", muscleGroup: "Hýždě a hamstringy", equipment: "Jednoručky", instructions: "Jednoručky veďte podél stehen, záda rovná po celou dobu." },
  { name: "Mrtvý tah jednonož", category: "Hýždě", muscleGroup: "Hýždě a hamstringy", equipment: "Jednoručky", instructions: "Stoj na jedné noze, druhá jde vzad jako protiváha. Zapojí i stabilizátory." },
  { name: "Zanožování na kladce", category: "Hýždě", muscleGroup: "Velký sval hýžďový", equipment: "Kladka", instructions: "Manžeta na kotníku, nohu veďte vzad s napnutým kolenem." },
  { name: "Zanožování na stroji", category: "Hýždě", muscleGroup: "Velký sval hýžďový", equipment: "Stroj", instructions: "Trup opřený, nohu tlačte vzad a nahoře zadržte." },
  { name: "Kickback s gumou", category: "Hýždě", muscleGroup: "Velký sval hýžďový", equipment: "Guma", instructions: "V kleku na čtyřech zanožujte proti odporu gumy." },
  { name: "Úkroky s gumou", category: "Hýždě", muscleGroup: "Střední sval hýžďový", equipment: "Guma", instructions: "Guma nad koleny, v mírném podřepu úkrokujte do stran." },
  { name: "Frog pump", category: "Hýždě", muscleGroup: "Velký sval hýžďový", equipment: "Vlastní váha", instructions: "Chodidla k sobě, kolena do stran. Boky zvedejte krátkým rozsahem." },

  // ------------------------------------------------------------- STŘED TĚLA
  { name: "Plank", category: "Střed těla", muscleGroup: "Hluboký stabilizační systém", equipment: "Vlastní váha", instructions: "Předloktí pod rameny, tělo v přímce. Nezvedejte ani neprohýbejte boky." },
  { name: "Boční plank", category: "Střed těla", muscleGroup: "Šikmé břišní svaly", equipment: "Vlastní váha", instructions: "Opora o jedno předloktí, tělo v přímce. Boky nesmí klesat." },
  { name: "Zkracovačky", category: "Střed těla", muscleGroup: "Přímý sval břišní", equipment: "Vlastní váha", instructions: "Bedra zůstávají na zemi, zvedejte jen lopatky. Krk netahejte rukama." },
  { name: "Zkracovačky na kladce", category: "Střed těla", muscleGroup: "Přímý sval břišní", equipment: "Kladka", instructions: "V kleku s lanem za hlavou stahujte hrudník ke kolenům obloukem." },
  { name: "Přednožování ve visu", category: "Střed těla", muscleGroup: "Dolní část břicha", equipment: "Hrazda", instructions: "Ve visu zvedejte pokrčené nebo napnuté nohy. Nehoupejte se." },
  { name: "Přednožování v opoře", category: "Střed těla", muscleGroup: "Dolní část břicha", equipment: "Žebřiny", instructions: "Předloktí v opěrkách, zvedejte kolena k hrudníku kontrolovaně." },
  { name: "Ruský twist", category: "Střed těla", muscleGroup: "Šikmé břišní svaly", equipment: "Medicinbal", instructions: "V sedu se zakloněným trupem rotujte s míčem ze strany na stranu." },
  { name: "Mrtvý brouk", category: "Střed těla", muscleGroup: "Hluboký stabilizační systém", equipment: "Vlastní váha", instructions: "Leh na zádech, střídavě natahujte protilehlou ruku a nohu. Bedra tlačte do země." },
  { name: "Bird dog", category: "Střed těla", muscleGroup: "Hluboký stabilizační systém", equipment: "Vlastní váha", instructions: "V kleku na čtyřech natahujte protilehlou ruku a nohu, boky držte v rovině." },
  { name: "Horolezec", category: "Střed těla", muscleGroup: "Břicho a kyčelní ohýbače", equipment: "Vlastní váha", instructions: "Ve vzporu střídavě přitahujte kolena k hrudníku. Boky nezvedejte." },
  { name: "Pallof press", category: "Střed těla", muscleGroup: "Šikmé břišní svaly", equipment: "Kladka", instructions: "Bokem ke kladce, tlačte madlo před sebe a bráňte rotaci trupu." },
  { name: "Ab wheel", category: "Střed těla", muscleGroup: "Přímý sval břišní", equipment: "Kolečko", instructions: "Z kleku vyjíždějte vpřed jen tak daleko, jak udržíte rovná bedra." },
  { name: "Nůžky", category: "Střed těla", muscleGroup: "Dolní část břicha", equipment: "Vlastní váha", instructions: "Leh na zádech, střídavě křižte napnuté nohy nad zemí." },
  { name: "Farmářská chůze", category: "Střed těla", muscleGroup: "Střed těla a předloktí", equipment: "Jednoručky", instructions: "Těžké činky v rukou, jděte vzpřímeně krátkými kroky." },

  // ---------------------------------------------------------------- KARDIO
  { name: "Veslovací trenažér", category: "Kardio", muscleGroup: "Celé tělo", equipment: "Veslovací trenažér", instructions: "Pořadí pohybu: nohy, trup, paže. Zpět opačně." },
  { name: "Rotoped", category: "Kardio", muscleGroup: "Nohy a oběhový systém", equipment: "Rotoped", instructions: "Sedlo nastavte tak, aby koleno bylo v dolní poloze mírně pokrčené." },
  { name: "Běžecký pás", category: "Kardio", muscleGroup: "Celé tělo", equipment: "Běžecký pás", instructions: "Držte vzpřímené držení těla, nedržte se madel. Začněte svižnou chůzí." },
  { name: "Orbitrek", category: "Kardio", muscleGroup: "Celé tělo", equipment: "Eliptický trenažér", instructions: "Šetrné ke kloubům. Zapojte i paže, nejen nohy." },
  { name: "Schodišťový trenažér", category: "Kardio", muscleGroup: "Nohy a hýždě", equipment: "Stepper", instructions: "Držení jen lehce pro rovnováhu, nepodpírejte se rukama." },
  { name: "Skákání přes švihadlo", category: "Kardio", muscleGroup: "Lýtka a oběhový systém", equipment: "Švihadlo", instructions: "Skákejte nízko na špičkách, zápěstí vedou otáčení." },
  { name: "Burpees", category: "Kardio", muscleGroup: "Celé tělo", equipment: "Vlastní váha", instructions: "Z dřepu do kliku, zpět a výskok. Tempo volte podle kondice." },
  { name: "Battle ropes", category: "Kardio", muscleGroup: "Paže a střed těla", equipment: "Lana", instructions: "V mírném podřepu střídavě vlnte lany. Pracujte celým tělem." },
  { name: "Vzpěračský tah s kettlebellem", category: "Kardio", muscleGroup: "Hýždě a záda", equipment: "Kettlebell", instructions: "Švih vychází z boků, ne z paží. Kettlebell letí do výše hrudníku." },
  { name: "Sáňky", category: "Kardio", muscleGroup: "Nohy a celé tělo", equipment: "Sáňky", instructions: "Tlačte v mírném předklonu krátkými silnými kroky." },
  { name: "Chůze do kopce", category: "Kardio", muscleGroup: "Nohy a oběhový systém", equipment: "Běžecký pás", instructions: "Sklon 8–12 %, svižná chůze bez držení madel. Šetrná varianta pro starší klienty." },

  // ------------------------------------------------------- DALŠÍ BĚŽNÉ VARIANTY
  { name: "Kliky na madlech", category: "Prsa", muscleGroup: "Prsa a triceps", equipment: "Madla", instructions: "Tělo držte v přímce a hrudník spouštějte mezi madla. Větší rozsah pohybu provádějte jen bez bolesti ramen." },
  { name: "Kliky s gumou", category: "Prsa", muscleGroup: "Prsa a triceps", equipment: "Odporová guma", instructions: "Gumu veďte přes horní část zad a držte pod dlaněmi. Tělo držte pevné a vytlačte se proti odporu." },
  { name: "Kliky na TRX", category: "Prsa", muscleGroup: "Prsa a střed těla", equipment: "TRX", instructions: "Madla držte pod rameny, tělo v jedné linii. Spouštějte hrudník mezi ruce bez propadání beder." },
  { name: "Tlaky na prsa na kladkách", category: "Prsa", muscleGroup: "Velký prsní sval", equipment: "Kladky", instructions: "Postavte se mezi kladky a tlačte madla před hrudník. Lopatky držte stabilní a pohyb veďte kontrolovaně." },
  { name: "Jednoruční tlak na prsa na kladce", category: "Prsa", muscleGroup: "Prsa a střed těla", equipment: "Kladka", instructions: "Stůjte bokem od kladky a tlačte jednou paží vpřed. Trup nesmí rotovat." },
  { name: "Floor press s velkou činkou", category: "Prsa", muscleGroup: "Prsa a triceps", equipment: "Velká činka", instructions: "Lehněte si na zem a spouštějte činku, dokud se paže lehce nedotknou podlahy. Poté vytlačte vzhůru." },
  { name: "Floor press s jednoručkami", category: "Prsa", muscleGroup: "Prsa a triceps", equipment: "Jednoručky", instructions: "Vleže na zemi spouštějte jednoručky do lehkého kontaktu paží s podlahou a vytlačte zpět." },
  { name: "Svend press", category: "Prsa", muscleGroup: "Velký prsní sval", equipment: "Kotouč", instructions: "Kotouče svírejte mezi dlaněmi před hrudníkem a propínejte paže vpřed při stálém tlaku dovnitř." },
  { name: "Rozpažování zdola nahoru na kladkách", category: "Prsa", muscleGroup: "Horní část prsou", equipment: "Kladky", instructions: "Madla veďte od boků šikmo vzhůru před horní část hrudníku. Ramena držte dole." },
  { name: "Rozpažování shora dolů na kladkách", category: "Prsa", muscleGroup: "Dolní část prsou", equipment: "Kladky", instructions: "Madla veďte obloukem shora dolů před boky. Lokty zůstávají mírně pokrčené." },

  { name: "Přítahy na TRX", category: "Záda", muscleGroup: "Střední část zad", equipment: "TRX", instructions: "Tělo držte zpevněné, přitáhněte hrudník k madlům a stáhněte lopatky k sobě." },
  { name: "Australské shyby", category: "Záda", muscleGroup: "Široký sval zádový", equipment: "Nízká hrazda", instructions: "Tělo držte rovné pod nízkou hrazdou a přitahujte hrudník k tyči." },
  { name: "Shyby neutrálním úchopem", category: "Záda", muscleGroup: "Široký sval zádový a biceps", equipment: "Hrazda", instructions: "Použijte paralelní madla, táhněte lokty dolů k bokům a spouštějte se kontrolovaně." },
  { name: "Shyby širokým úchopem", category: "Záda", muscleGroup: "Široký sval zádový", equipment: "Hrazda", instructions: "Uchopte hrazdu o něco šířeji než ramena a táhněte hrudník směrem k hrazdě." },
  { name: "Stahování horní kladky podhmatem", category: "Záda", muscleGroup: "Široký sval zádový a biceps", equipment: "Kladka", instructions: "Podhmatem táhněte tyč k horní části hrudníku a lokty veďte podél těla." },
  { name: "Stahování horní kladky jednoruč", category: "Záda", muscleGroup: "Široký sval zádový", equipment: "Kladka", instructions: "Jednou rukou táhněte madlo k boku. Rameno nevytahujte k uchu a trup neotáčejte." },
  { name: "Veslování jednoruč na kladce", category: "Záda", muscleGroup: "Střední část zad", equipment: "Kladka", instructions: "Táhněte madlo k boku a na konci stáhněte lopatku. Trup zůstává bez rotace." },
  { name: "Veslování s oporou hrudníku", category: "Záda", muscleGroup: "Střední část zad", equipment: "Jednoručky", instructions: "Lehněte hrudníkem na šikmou lavici a přitahujte jednoručky k bokům bez švihu." },
  { name: "Seal row", category: "Záda", muscleGroup: "Střední část zad", equipment: "Velká činka", instructions: "Ležte břichem na vysoké lavici a přitahujte činku k její spodní straně." },
  { name: "Pullover na kladce", category: "Záda", muscleGroup: "Široký sval zádový", equipment: "Kladka", instructions: "S téměř nataženými pažemi stahujte lano od hlavy ke stehnům bez změny úhlu loktů." },
  { name: "Pullover na stroji", category: "Záda", muscleGroup: "Široký sval zádový", equipment: "Stroj", instructions: "Lokty opřete o opěrky a táhněte je obloukem dolů. Hrudník držte opřený." },
  { name: "Landmine row", category: "Záda", muscleGroup: "Střední část zad", equipment: "Landmine", instructions: "V předklonu přitahujte konec osy k hrudníku. Záda držte rovná a lokty veďte dozadu." },

  { name: "Push press", category: "Ramena", muscleGroup: "Ramena a triceps", equipment: "Velká činka", instructions: "Lehkým podřepem vytvořte impuls a vytlačte činku nad hlavu. Dokončete s pevným středem těla." },
  { name: "Z-press", category: "Ramena", muscleGroup: "Deltový sval a střed těla", equipment: "Velká činka", instructions: "Sedněte na zem s nataženýma nohama a tlačte činku nad hlavu bez záklonu." },
  { name: "Jednoruční tlak nad hlavu", category: "Ramena", muscleGroup: "Deltový sval", equipment: "Jednoručka", instructions: "Tlačte jednoručku nad hlavu a bráníte úklonu trupu do strany." },
  { name: "Landmine press v kleku", category: "Ramena", muscleGroup: "Přední delt a střed těla", equipment: "Landmine", instructions: "V kleku tlačte konec osy šikmo vzhůru. Žebra držte stažená a hýždě zpevněné." },
  { name: "Upažování v předklonu na kladce", category: "Ramena", muscleGroup: "Zadní hlava deltu", equipment: "Kladka", instructions: "V mírném předklonu veďte paži do strany a vzad. Pohyb začíná v rameni." },
  { name: "Y-raise na lavici", category: "Ramena", muscleGroup: "Dolní trapéz a ramena", equipment: "Jednoručky", instructions: "Na šikmé lavici zvedejte lehké jednoručky šikmo vzhůru do tvaru písmene Y." },
  { name: "Y-raise na kladkách", category: "Ramena", muscleGroup: "Dolní trapéz a ramena", equipment: "Kladky", instructions: "Křížem uchopte spodní kladky a zvedejte paže do tvaru Y bez krčení ramen." },
  { name: "Kubánský tlak", category: "Ramena", muscleGroup: "Rotátory ramene", equipment: "Jednoručky", instructions: "Z přítahu rotujte předloktí vzhůru a lehce vytlačte. Použijte nízkou váhu a plynulý pohyb." },
  { name: "Zevní rotace ramene s gumou", category: "Ramena", muscleGroup: "Rotátorová manžeta", equipment: "Odporová guma", instructions: "Loket držte u boku v pravém úhlu a otáčejte předloktí ven bez pohybu paže." },

  { name: "Spider curl", category: "Biceps", muscleGroup: "Dvojhlavý sval pažní", equipment: "Jednoručky", instructions: "Hrudník opřete o šikmou lavici, paže nechte viset a zvedejte bez pohybu ramen." },
  { name: "Bayesian bicepsový zdvih", category: "Biceps", muscleGroup: "Dlouhá hlava bicepsu", equipment: "Kladka", instructions: "Stůjte zády ke spodní kladce, paže je mírně za tělem a loket během zdvihu zůstává na místě." },
  { name: "Kladivový zdvih s lanem", category: "Biceps", muscleGroup: "Biceps a vřetenní sval", equipment: "Kladka", instructions: "Lano držte neutrálním úchopem a přitahujte k ramenům bez posunu loktů." },
  { name: "Bicepsový zdvih na stroji", category: "Biceps", muscleGroup: "Dvojhlavý sval pažní", equipment: "Stroj", instructions: "Nastavte opěrku pod paže a zvedejte madla v plném kontrolovaném rozsahu." },
  { name: "Zottmanův zdvih", category: "Biceps", muscleGroup: "Biceps a předloktí", equipment: "Jednoručky", instructions: "Nahoru zvedejte podhmatem, nahoře otočte dlaně dolů a spouštějte nadhmatem." },
  { name: "Zdvih zápěstí podhmatem", category: "Biceps", muscleGroup: "Ohýbače předloktí", equipment: "Jednoručky", instructions: "Předloktí opřete o stehna a pohybujte pouze zápěstím v plném rozsahu." },
  { name: "Zdvih zápěstí nadhmatem", category: "Biceps", muscleGroup: "Natahovače předloktí", equipment: "Jednoručky", instructions: "Předloktí opřete a zvedejte hřbety rukou proti odporu bez pohybu loktů." },

  { name: "JM press", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "Velká činka", instructions: "Činku spouštějte mezi bradu a horní hrudník s lokty mírně vpřed, potom propněte paže." },
  { name: "Tate press", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "Jednoručky", instructions: "Vleže spouštějte jednoručky směrem ke středu hrudníku s lokty do stran a poté paže propněte." },
  { name: "Francouzský tlak na kladce", category: "Triceps", muscleGroup: "Dlouhá hlava tricepsu", equipment: "Kladka", instructions: "Zády ke kladce propínejte paže nad hlavou. Lokty držte úzce a na místě." },
  { name: "Tricepsové stahování rovnou tyčí", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "Kladka", instructions: "Lokty držte u boků a tyč stlačujte do úplného propnutí bez předklánění." },
  { name: "Tricepsové stahování podhmatem", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "Kladka", instructions: "Tyč uchopte podhmatem a propínejte lokty s pažemi pevně u těla." },
  { name: "Tricepsové extenze na TRX", category: "Triceps", muscleGroup: "Trojhlavý sval pažní", equipment: "TRX", instructions: "Tělo držte rovné, ohýbejte lokty směrem k madlům a silou tricepsu se vraťte." },

  { name: "Dřep s bezpečnostní osou", category: "Nohy", muscleGroup: "Stehna a hýždě", equipment: "Safety bar", instructions: "Osu usaďte na ramena, zpevněte trup a dřepujte s koleny ve směru špiček." },
  { name: "Dřep na bednu", category: "Nohy", muscleGroup: "Stehna a hýždě", equipment: "Velká činka a bedna", instructions: "Boky posuňte vzad k bedně, lehce dosedněte bez uvolnění trupu a vraťte se vzhůru." },
  { name: "Dřep s pauzou", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Velká činka", instructions: "V dolní poloze dřepu zůstaňte krátce bez uvolnění napětí a poté plynule vystoupejte." },
  { name: "Zercherův dřep", category: "Nohy", muscleGroup: "Stehna a střed těla", equipment: "Velká činka", instructions: "Činku držte v ohbí loktů, trup vzpřímený a klesejte mezi kolena." },
  { name: "Reverzní výpady z vyvýšení", category: "Nohy", muscleGroup: "Stehna a hýždě", equipment: "Jednoručky", instructions: "Z nízkého stupínku vykročte vzad, zadní koleno spusťte k zemi a odtlačte se přední nohou." },
  { name: "Boční výpady", category: "Nohy", muscleGroup: "Stehna a přitahovače", equipment: "Vlastní váha", instructions: "Vykročte do strany, boky pošlete vzad nad pokrčenou nohu a druhou nohu nechte nataženou." },
  { name: "Cossack dřep", category: "Nohy", muscleGroup: "Stehna a přitahovače", equipment: "Vlastní váha", instructions: "Přeneste váhu do hlubokého dřepu na jednu stranu, druhou nohu držte nataženou." },
  { name: "Pistol dřep", category: "Nohy", muscleGroup: "Čtyřhlavý sval a stabilizátory", equipment: "Vlastní váha", instructions: "Dřepujte na jedné noze s druhou nataženou vpřed. Začněte s oporou a jen v kontrolovaném rozsahu." },
  { name: "Spanish squat", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Silná guma", instructions: "Gumu veďte za koleny, posaďte boky vzad a držte holeně téměř svislé." },
  { name: "Zakopávání na míči", category: "Nohy", muscleGroup: "Hamstringy", equipment: "Gymnastický míč", instructions: "Vleže s patami na míči zvedněte boky a přitahujte míč k tělu." },
  { name: "Zakopávání na TRX", category: "Nohy", muscleGroup: "Hamstringy", equipment: "TRX", instructions: "Paty vložte do poutek, zvedněte boky a přitahujte chodidla k hýždím." },
  { name: "Nordic curl s dopomocí", category: "Nohy", muscleGroup: "Hamstringy", equipment: "Odporová guma", instructions: "Guma pomáhá při spouštění trupu vpřed. Boky držte propnuté a návrat kontrolujte." },
  { name: "Výpony na leg pressu", category: "Nohy", muscleGroup: "Lýtka", equipment: "Leg press", instructions: "Špičky umístěte na okraj plošiny a pohybujte pouze kotníky v plném rozsahu." },
  { name: "Výpony jednonož", category: "Nohy", muscleGroup: "Lýtka", equipment: "Vlastní váha", instructions: "Stůjte na jedné noze na hraně stupínku, patu spusťte dolů a vytlačte se vysoko na špičku." },
  { name: "Tibialis raise", category: "Nohy", muscleGroup: "Přední holenní sval", equipment: "Vlastní váha", instructions: "Opřete se zády o stěnu, paty nechte na zemi a zvedejte špičky co nejvýše." },

  { name: "Hip thrust na stroji", category: "Hýždě", muscleGroup: "Velký sval hýžďový", equipment: "Stroj", instructions: "Pás umístěte přes pánev, zvedejte boky a nahoře hýždě pevně zatněte bez záklonu." },
  { name: "Hip thrust v multipressu", category: "Hýždě", muscleGroup: "Velký sval hýžďový", equipment: "Smith stroj", instructions: "Lopatky opřete o lavici a vedenou osu zvedejte pánví do plného propnutí kyčlí." },
  { name: "Glute bridge s velkou činkou", category: "Hýždě", muscleGroup: "Velký sval hýžďový", equipment: "Velká činka", instructions: "Vleže na zemi položte činku přes pánev, vytlačte boky vzhůru a sevřete hýždě." },
  { name: "Pull-through na kladce", category: "Hýždě", muscleGroup: "Hýždě a hamstringy", equipment: "Kladka", instructions: "Lano veďte mezi nohama, boky pošlete vzad a poté je silou hýždí propněte." },
  { name: "Zanožování v kleku", category: "Hýždě", muscleGroup: "Velký sval hýžďový", equipment: "Vlastní váha", instructions: "V kleku na čtyřech zvedejte pokrčenou nohu vzhůru bez rotace pánve." },
  { name: "Unožování na kladce", category: "Hýždě", muscleGroup: "Střední sval hýžďový", equipment: "Kladka", instructions: "S manžetou na kotníku veďte nataženou nohu do strany a trup držte vzpřímený." },
  { name: "Mušle s gumou", category: "Hýždě", muscleGroup: "Střední sval hýžďový", equipment: "Odporová guma", instructions: "Ležte na boku s pokrčenými koleny a rozevírejte horní koleno bez otáčení pánve." },

  { name: "Hollow body výdrž", category: "Střed těla", muscleGroup: "Přímý sval břišní", equipment: "Vlastní váha", instructions: "Bedra tlačte do země, lopatky a nohy držte nad podlahou. Zvolte polohu, kterou udržíte bez prohnutí." },
  { name: "Výdrž ve visu", category: "Střed těla", muscleGroup: "Úchop a ramena", equipment: "Hrazda", instructions: "Viste s aktivními rameny staženými od uší a držte pevný úchop po určený čas." },
  { name: "L-sit výdrž", category: "Střed těla", muscleGroup: "Břicho a kyčelní ohýbače", equipment: "Bradla", instructions: "V opoře propněte paže a držte natažené nohy vodorovně před tělem." },
  { name: "Wall sit výdrž", category: "Nohy", muscleGroup: "Čtyřhlavý sval stehenní", equipment: "Stěna", instructions: "Opřete záda o stěnu, kolena držte přibližně v pravém úhlu a vydržte bez opírání rukou o stehna." },
  { name: "Plank s nataženými pažemi", category: "Střed těla", muscleGroup: "Hluboký stabilizační systém", equipment: "Vlastní váha", instructions: "Dlaně držte pod rameny, celé tělo v přímce a břicho pevně zpevněné." },
  { name: "Plank na gymnastickém míči", category: "Střed těla", muscleGroup: "Hluboký stabilizační systém", equipment: "Gymnastický míč", instructions: "Předloktí opřete o míč a držte tělo stabilní bez propadání beder." },
  { name: "Bear plank výdrž", category: "Střed těla", muscleGroup: "Hluboký stabilizační systém", equipment: "Vlastní váha", instructions: "V kleku zvedněte kolena pár centimetrů nad zem a držte záda rovná." },
  { name: "Farmářská chůze jednoruč", category: "Střed těla", muscleGroup: "Šikmé břišní svaly a úchop", equipment: "Jednoručka", instructions: "Noste těžkou činku v jedné ruce, trup držte vzpřímený a neuklánějte se." },
  { name: "Woodchop na kladce", category: "Střed těla", muscleGroup: "Šikmé břišní svaly", equipment: "Kladka", instructions: "Táhněte madlo šikmo přes tělo a rotujte hrudník kontrolovaně bez pohybu kolen." },
  { name: "Obrácené zkracovačky", category: "Střed těla", muscleGroup: "Dolní část břicha", equipment: "Vlastní váha", instructions: "Přitahujte kolena k hrudníku a lehce zvedněte pánev bez švihu nohou." },
  { name: "V-sedy", category: "Střed těla", muscleGroup: "Přímý sval břišní", equipment: "Vlastní váha", instructions: "Současně zvedejte trup a natažené nohy, ruce směřují ke špičkám." },

  { name: "Air bike", category: "Kardio", muscleGroup: "Celé tělo", equipment: "Air bike", instructions: "Šlapejte a současně pracujte pažemi. Intenzitu řiďte tempem a držte stabilní trup." },
  { name: "Ski erg", category: "Kardio", muscleGroup: "Záda, paže a oběhový systém", equipment: "Ski erg", instructions: "Madla stahujte shora dolů s mírným předklonem a zapojením středu těla." },
  { name: "Běh venku", category: "Kardio", muscleGroup: "Nohy a oběhový systém", equipment: "Bez vybavení", instructions: "Držte uvolněný krok, vzpřímený trup a tempo odpovídající cíli tréninku." },
  { name: "Sprinty", category: "Kardio", muscleGroup: "Celé tělo", equipment: "Bez vybavení", instructions: "Po důkladném zahřátí běžte krátký úsek vysokou intenzitou a mezi úseky plně odpočívejte." },
  { name: "Box jump", category: "Kardio", muscleGroup: "Nohy a výbušnost", equipment: "Bedna", instructions: "Vyskočte měkce na stabilní bednu, dopadněte celými chodidly a dolů raději sestupte." },
  { name: "Medicinbalové hody o zem", category: "Kardio", muscleGroup: "Celé tělo", equipment: "Medicinbal", instructions: "Zvedněte míč nad hlavu a silou celého těla ho hoďte před sebe o zem." },
  { name: "Medvědí chůze", category: "Kardio", muscleGroup: "Celé tělo", equipment: "Vlastní váha", instructions: "Pohybujte se po čtyřech s koleny nízko nad zemí a pevným středem těla." },
  { name: "Kettlebell clean", category: "Kardio", muscleGroup: "Celé tělo", equipment: "Kettlebell", instructions: "Švihem z kyčlí veďte kettlebell plynule do pozice u ramene bez nárazu do předloktí." },
  { name: "Kettlebell snatch", category: "Kardio", muscleGroup: "Celé tělo", equipment: "Kettlebell", instructions: "Z kyčelního švihu veďte kettlebell jedním pohybem nad hlavu. Začněte až po zvládnutí swingu a cleanu." },
  { name: "Thruster s jednoručkami", category: "Kardio", muscleGroup: "Celé tělo", equipment: "Jednoručky", instructions: "Z dřepu plynule přejděte do tlaku jednoruček nad hlavu a využijte sílu nohou." },
];
